env:
  global:
    - secure: dInDfAU9Qvl5/389Kpqo13wOVwcJT9RZX1c134w7RsC5Pgzcyjbn/erkgbtDp/vzrFn+tRfMcB0rB+QD4KFgA588AqzvCxJsn5A4jNm0B4QvCO1d9fibAcHpvA2Ff68f0HdqU3YJD2K2KQabIl6Nzz4cgAU60Ekx30Ngl5b9rv8zwje4ZMY2Rra+9/q+8TFfwbTDE9CO9GeNzIcmoTFdpVb+2Ifgm/XPgwqwAOuhQ2/+QMh9xCAs9jAXoKGOYuNnCEFyLITKXEtp9byNv5X8LmtEQZ5Yb8hvphECqVdHmxBko4Hqhk/csQbtzFuvS8wGJscp1D9aYp6mbDQPOLWHJDaFP9ugbsHZyteMW9Q7Srh8dbFRFMahk8PCzLMmEJdh8vK19cpKmFYn+ub9nk3ObpDVeTB2aQpKirXZOoZXKYNe9RVkVqQGIZ2RZrdpAMxjPgGpsG0pfsp5O6vAUDQ2uux7PKTyz+dgUYlB2H7SDPMwomFLh6DAJsENmtVMhLW47jouvFCsgxBtcotmE2pb0h+MQuyoXFSNpps/PcK0bhYhQqh/n3RIHCIBxJa3y6SIfUXI8hdbneJ3sARvnouiQDBultYjTQ3d8hQ5a/bkGCz3GfJDjb3zYFTP3Zo/omcmqlMQPpJjKLHDUY0W2ASllpAdN3rGlnJcBXCEn4UZtdU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
