env:
  global:
    - secure: GqkNp90db/5P76/fejr4zKTKlv3kNodEs6wDiVXn+q3WxOBrc57f8W1WyLddquTrugHl+tfYj5WY2f0g/YYDnAoKZByi0dHCNwUO1wn44nUZtTlljc+he0fgjWnRktSk4ghD4/ApXmMmCjdBjARGA9TlE+YwWxypuHd9jbUeDMb/GhFfs5t/e2qIycPfK8pmqHOjHoYEaYzqpYFCoDaWlLtMLW0OWmvPBoQgrYi0Xyxcm2xcPIpcMotcJ9VbbbLtIktaLi+2seEok3/sCUOJLC0bawBqeGuf4nGT2Cuq02z11eqdY00q12i4r62hyup9vgRl6z6wGz1De/VliMcA9hOGLyur5+gVd3uJWCgn7bxr0vJmpEJQkjuE+FXmt/os/i7HWua8HOTWQADbYny7qeVjW2uVEONb68iL++9mLVjFyMdi9f4AemsXdkhCUQ7ARPYSeOg9hpnxVoMp4AD6QABOKActkhGRyzIVVPMdoBl3jutH3jpomeDuv2ZsZhrlJb2FqNhR0RJunK8A5smMM1bWlr2dULeiW2v4qUyZz4rLpaqFnGXUqZDqAwcInKdTAJxBXqd2uMY7/neYSYrZnzYcqWL6wtjqXDQ58jjdcqj3q9SXqz4MMRrUtT8/E45UM8zWPGPnL1fIUYtpJK03bAWOqXNF1qAaOTn8+eRuCWY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
