env:
  global:
    - secure: hXU4ATtsFQGTiqIeOyoI88oMDN+3E0cYYzdkMXZ1KKxl8WjpZZapDdbY1ArN3Q3mUXuSBD3KnptbqPnE+dOwtiS8cMjlE0R+j/eSARkHUs96uuCnd2JvpC+7HhVMxQ/xL19NDARCCY4vZDFOnxbCcZ94t9h2bKpmpsTuc4Hf0YsPBcsqkrhqKmw19E+ZEoTk9CCMaTJDcNmjjOFFqXUHN48IMXqvpxa4hXCUlKJmZ7hvw9++PgQDmWzsfx+NGNj6GwTdE8O4uZ/uu9QtVX+rTlNvZdNe6wBP6Mnf9hfe+Ilkpd5SdoPsqA8RGmfjVMirbiXA1OW0FqgUnOQKZ3ehuv8C3ugHAcIemb8KTPdaSJ8jf6q6pP4MGKPcGZqhcetfahSHp8XMmYIYjI1lgaBma9Wrc3pk9YhiMttmG5oLtHcCa0pfRJSsAcSRIpxIi8C/nueJ9Aign/D+qJ5GM/XjibBQyWyZzuoM3Iv/i2XJ9u0LdkD3wSdmiPAAokFOQZj39/eOjwURcJ0tbGkQ4/9vcFkH0qCdhD0n3e8bTbWolDAB7Yn2YgBC/lzEN5rd0dM445OeGMdiUrViDRuaKaGuhAgmIPgf+9KQG8e7ZF0zB5YgNEBqXQrdECeiHaeW3RtoBA3N7AtaLqpwneMZQo04pPrArXq/j2X+TyPoEbNzvEM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
