env:
  global:
    - secure: JDSIh3dnd1uxw11ijhqTAtXtDWG7FxYV9/1Z4Ym0EiDc90sFfrbJKM6A9aybAj0ngMwDxVNHA1o51oYF/ohQb6m4jePfiL1N1VFNZQDxhwfQphIWwYU+8l6Mz/OXM3HrKa52dr+CDgXa4asSUdvi4aUKl1Fp27ISGH1PitQZ8PdMhk0D0tXd6kWCu1y+1aEwG140M4TfxWKFbhDE21ocunZxbiA2QVHYPqbIjMIRN03EOvZ6+KJYJLAvw0J75U5Cm26JFVb/dImRghxC4glQ7PslG/93ITe9yZ2jEidqHism92SFIhJIgb0hjKR1jn76+rG3cSDGg7SbUfawPj2lNBsDkOVRVsk0aOMPRE0GnQ4fhjoHWiHg24sH/iDKRSQjyLu/mLoElTaqhGHsS+v/nktklt9wfRFekwsMN5VhQPR1zCW34j9s4w0f6K4kFRLP7vAaljc2I8EVGehMEwXWBdjV9Zfe95EvY6qfNzdCDNpN6MIB8RmbDkMAHLJ7shtfOa4yoCyyfG5FlZh7zxFjvEQY0tU5e6TZnAJOu2ShfBiUqHATq0enuA6wbq047fEBC/ADXZuckk96VeYw9yJ89Spf8mYUhR6xfLOUuRErgRumBFwiw2UiZO6UhSQR47JHcdTV8zQfheY3e0vY7shwTAd1GU7Qm/0CvavH6l97nZk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
