env:
  global:
    - secure: mr9lmzc7osPtBTJBD5u3eSB8KCee+FOgo+YzuxaAfd0iAC0sv+742+shege/jCQKCy96crcubSrpdZ2x7x9IWa5/yKLUXzAKVOmYyDgZL67myTmq4Bzlf7fDqvfVCeWbOmOkG1K74aTmCBPP4hbCiPiy4Pc+feD1OKqGdoEbBJvODl9XKmhc1zPzvGAU867UG/ntGCxsUL/ez0wunrlp/5YAsyDIRoK1SwE1VgOezch3U6trSfbeyfv948D8XxB3SG/g70zru5aXRDnz/fPdOcCiOnXHuJirwwmInXxGMhrKG1PPnjmFS6a674h1rHee0NGVgY9GTHCvF04g2tH7askaftGMiOge/7pAFs6770vmVFLTQHQNv3Smi4/3EGx/8To8IVlw5WlC5emmDa2rGthrZ8EbpvKPKcvf8AjcHFuW+j5yTsAv3bayWuvj+8tjsuKLaf+amlRYmwipNIvhc3hW6gJXicg+JPj0AGDyWUeyIKCI/uq1KbkvaZf9w60k3AX1bJuq33yNjkSpwyUXCSH+ukOZcWLOHmW6LlnDbwZ1yzAevLh0Ey9Ayjqyb2IT+12oU+uhxRi9Pr3zgeue83PEecVfN2NdM3T8dQH+0tD7ID2g1LvUCw6LQ9KLOkNzUOs/S5GGM8UO8UBBVEVhv86wNEAW5DlkQCmZbJbssag=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
