env:
  global:
    - secure: be1EHAzqA+zRu53oMTPzD+coLVA8y1hs5mSwGyzYMVaGhYrgcfeZ7PK3cpl1kVwdENUPNrTqMkNoMz/zDXfCMwHpbVn5R1u1j5eEOTtJgdz4f0RGVxBe9IxkL6KMFpRQO93fSHVUcJQRe4HtnF+xmw9Gbwxb7bweymTRCno2NAHHhuj2ydAAk026eqI88sBY8WqPwBTHI1AcP4Bbq1ow69gGOMv5UQFvy3m/WiGf7VzW6oleyn3ww82MlmZpE0Nv8P+vdIIUtI5MjIj9F9hopk9hDuYuGl7o9zv36jY5xACKtSYfyI2ipanqypPUHEHB4at/JfCkR1n5S6wZ+KT5Hbo2pzVsBekysOdsAdWMgDGullLZIseKMhHn0+CRTfduiwtqbJjGeYv04GaspmFefl3jwlP87RCOdL0dWJE+jTPDYQLMZTlOOXxryh6oSqOdAXKnHaT0kCOE49kuMMt7Fesde2F32axjRQpmeZUI+QVtCXE3qj7Ir7Jtm7apgbabGFBMX4waul2iu3scX+q7kcutA9dzsOspdqcL11sFS7opoqNzyVgomjyQuwEt5p5rJyouWQDD4gePxqqEaZOV1/Z7TnL52/0oYHN/KisH1kKoH0TXEt2wEJWhTHUfpUriMDSdk5NPJofrjZbM3oS7sYH7obOifz5+RKmAT+C01SI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
