env:
  global:
    - secure: fSYbCL9b8fKIX26SyeNx8NlRZnGMon728gddi6wlg3YtbB76GrqXzVNJ7Kiyv/Hxq/dzoIJnEbA4czHtNahqgen4fRJ47dl0NslrarREccZWTN0NrHjPhgjk0w7MPXowPogALXJgtCUet3TEmWmM37OUDHkMUyAXWDd7XvqmG9z84f8xBQiojr6csyC2PURB2WiMEX0QenblM2J1mOoSZNVGu8GCB+gXZjdutE73iaYj9m5tuSoXeyr5DxCHzhrDI6z1mkYczef3g555ym6x37YdzGh/PY5DorqLIIqZ2i8sBpBYj6TNbg6SH2770BpbKWZ7tZ2rO5iPtdF3Ku0VB/f+haBwbsGDxe4R8MTCAmBMg9t+7hQad7ec4S6dsXEoul0fHOZvkTx11nbpLH2bOYCHcp3A3DER67741GVdKhB5Lj5nWFVf1JLoLoyRnvOnGaemn/WXqMT6pYS+03SvShWjD6wQ37NAgrHyi1cd4WP4mWIzx/iPVUOIwmQ2zy2gLHprFk9BoMc4Bfzb/0N9mzwTADyVTkoOBp0jJNXxi0BIuQkTBjV0qTzQ5pncc0bt62tA5lhe2QxCP6AWaFnzztDZe3074COw5slwbvFJAbUTKqhmwB0iU7U7cal1e8iWSHfKUlWT7EJ0p5ssqxJELkOad50Yy5iGGFET7gaSYl0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
