env:
  global:
    - secure: VqudFsSt9uZdPJLLJp5mLxpQsxJ6XFF1dqQnGIsMcXd0LfnP/ZKoNWPeNTMtqr12ySwcVUP3ds0Y0BA2mJQ+t81hZz3686vdr0tW0OnxCr6bMRnAQh53jGGJ4JXsJVuEzq4MvfRyC5iAoySSeU+VQlekWPoWkyaz64RTkKEK8yZOCP8WaBoBvCzTAMUTHNAUvIGgx4vxt3P2ptFGOo/e/VqgJfQnJlwd0R7XNPtcI9FL5nACw4vsyJwAEVM/WpH9njdfOC9ICjlfj6FK9XE/kY0/NNZjxUEQ5gOLhSRVqfUQkSYf79CDAWQ9Bo66lpocIxyfTpUefVzxKcHdZ5EcYcwvburddGTmfLuvyOg+EMlKipQ90m0XaY37bVn0H9142eFkfoMQFL9xg+G3u7FRzMOeeaXUPfesFdMyihzlr1KXQ97oKhLQUS45MhG0Jt8h19EbzSWf9HJCPbEGiSRj7F1tyMOIxHcne5nwdaKj8c5sXyDutdZBdqvsSKelzEDAuUkSkXouX8ZticBBtg80OQ3E7YAojgftcJaSMfv8ptV/QxB8oFsP7ObrT3bPXLcNyUmIZM0FtzCaYg0JYr3/OIFT5BodzXxoHUVCTR5dHy0Ll3r1lkOG1GnFXVnGab7MH6KkUBjDjG1d0SayM2t9Z5O9ALKxHcTuNVrKRY8dYvI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
