env:
  global:
    - secure: CTJ035Wnd9W+7D/h1jo7fXDlYQaGSgUCAx6aUtV91JFqjwgv6tmPNIH7hSP6rKC8vsSI24iaa0BNUBgmq4kR3yYSCQKxoue1zRfz3cYiyx+/Pph3UKMh7i6ZA1onqcbcSbp+ar0DY1HNr/v2zZGqOyUraswiKsDe65xJqIGzOQd7SVbCJf9oGYumiqnWlYpUYwRcDA8dC1MTnS49BdKDl6Y5w9SzNyrBfW5PwMZDOCVMRoD6C2igWGtVE1UKNsNLhPtrVaX6RG7vrLVzZwVeseewgY+98hhp3p9ywaojmXN6HNQaRTki6ZHgWz+y7o8RixytmUvvj9JxcsUpWF6soBN71iDRZJQHcrmByBJLCxAVBMRL92yMLbrJ/jf8u1rLl55G2q7sn+JZAJ+sFJWpHPhKrgx/cVnxWZfrQ1TmXY2cZmSGYdaQrcqLWq+7LSL81KBrw47j7xri4XfuOX0Jh/7oFgOWI9GDwsYsCQWtXrzQ+IGwAZcluvmNRRWwvN7yQEXdgYEkxQLZXXavfTD8s/UWgXFC64mnT3n66xrtIozjxDgrj9d91rEJ4v5n9mhIlH/6PsO9NbUnTzUMjdKNdYpM6OU+JT/bJh8Dc4Hg8Ef2aWw6IgvEFQIPV6MMJH03xArHf3J2Tt7b8n5MuXIVHtuWf0jf0vnYYz8bFrMfIok=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/BaddBoyzHosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
